version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "pom.xml" }}
            - dependencies-
      - run:
          name: Build and run tests
          command: mvn clean verify
      - save_cache:
          key: dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  publish:
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "pom.xml" }}
            - dependencies-
      - run:
          name: Publish to local maven repo
          command: mvn clean verify

  docker-publish:
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to docker
          command: docker login -u folksdev -p ${DOCKERHUB_PASSWORD}
      - run:
          name: Build docker image
          run: docker build -t folksdev/account-api:latest .
      - run:
          name: Publish docker image
          run: docker push folksdev/account-api:latest


workflows:
  version: 2
  cicd-workflow:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
      - docker-publish:
          requires:
            - publish
          
