version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          keys:
            - mvn-dependencies-{{ checksum "pom.xml" }}
            - mvn-dependenceies-
      - run:
          name: Build and test
          command: mvn clean verify
      - save_cache:
          key: mvn-dependencies
          paths:
            - ~/.m2

  publish:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          keys:
            - mvn-dependencies-{{ checksum "pom.xml" }}
            - mvn-dependenceies-
      - run:
          name: Publish to local repo
          command: mvn install -D maven.test.skip=true

workflows:
  version: 2
  cicd-pipeline:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test