version: 2

jobs:
  verify:
    docker:
      - image: maven:3.8.3-jdk-11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # Dependencies will be loaded from cache unless pom changes
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Test
          command: mvn clean install -Dmaven.test.skip=true
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  install:
    docker:
      - image: maven:3.8.3-jdk-11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Deploy
          command: mvn deploy
  publish:
    docker:
      - image: maven:3.8.3-jdk-11
    steps:
      - checkout
      - run:
          name: Install docker # Download and install docker client
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
      - setup_remote_docker
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build Docker Image
          command: docker build -t folksdev/account-api:latest .
      - run:
          name: Publish Docker Image
          command: docker push folksdev/account-api:latest

workflows:
  version: 2
  build-and-test-and-deploy:
    jobs:
      - verify
      - install:
          requires:
            - verify
      - publish:
          context:
            - DOCKER_HUB
          requires:
            - verify
          filters:
            branches:
              only: master