version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout
      - run:
          name: Build and run tests
          command: mvn clean verify

  publish:
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout
      - run:
          name: Publish to local maven repo
          command: mvn clean verify

workflows:
  version: 2
  cicd-workflow:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
