version: 2

jobs:
  installs:
    docker:
      - image: maven:3.8.3-jdk-11
    steps:
      - checkout
      - restore_cache:
          key: mvn-cache
      - run:
          name: Test
          command: mvn clean install
      - save_cache:
          key: mvn-cache
          paths:
            - ~/.m2

  test:
    docker:
      - image: maven:3.8.3-jdk-11
    steps:
      - checkout
      - restore_cache:
          key: mvn-cache
      - run:
          name: Test
          command: mvn install
  publish:
    docker:
      - image: maven:3.8.3-jdk-11
    steps:
      - checkout
      - run:
          name: Install docker # Download and install docker client
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
      - setup_remote_docker
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - restore_cache:
          key: mvn-cache
      - run:
          name: Build Docker Image
          command: docker build -t folksdev/account-api:latest .
      - run:
          name: Publish Docker Image
          command: docker push folksdev/account-api:latest

workflows:
  version: 2
  build-and-test-and-deploy:
    jobs:
      - compile
      - test:
          requires:
            - compile
      - publish:
          context:
            - DOCKER_HUB
          requires:
            - test
          filters:
            branches:
              only: master