version: 2

jobs:
  compile:
    docker:
      - image: openjdk:11
    steps:
      - restore_cache:
          key: mvn-cache
      - checkout
      - run:
          name: Clean
          command: ./mvnw clean
      - run:
          name: Compile
          command: ./mvnw compile
      - save_cache:
          key: mvn-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.mvn"
            - "~/.m2"
  test:
    docker:
      - image: openjdk:11
    steps:
      - restore_cache:
          key: mvn-cache
      - checkout
      - run:
          name: Test
          command: mvn install
  publish:
    docker:
      - image: openjdk:11
    steps:
      - setup_remote_docker
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - restore_cache:
          key: mvn-cache
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t folksdev/account-api:latest ../.
      - run:
          name: Publish Docker Image
          command: docker push folksdev/account-api:latest

workflows:
  version: 2
  build-and-test-and-deploy:
    jobs:
      - compile
      - test:
          requires:
            - compile
      - publish:
          context:
            - DOCKER_HUB
          requires:
            - test