version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "pom.xml" }}
            - dependencies-
      - run:
          name: Build and run tests
          command: mvn clean verify
      - save_cache:
          key: dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  publish:
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "pom.xml" }}
            - dependencies-
      - run:
          name: Publish to local maven repo
          command: mvn clean verify

workflows:
  version: 2
  cicd-workflow:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
