version: 2

jobs:
  verify:
    docker:
      - image: circleci/openjdk:11

    environment:
      - JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Maven clean verify
          command: mvn clean verify
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  install:
    docker:
      - image: circleci/openjdk:11

    environment:
     - JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Maven install
          command: mvn install

workflows:
  version: 2
  ci-cd-workflow:
    jobs:
      - verify
      - install:
          requires:
          - verify
