version: 2

jobs:
  verify:
    docker:
      -image: circleci/openjdk:11

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Maven clean verify
          command: mvn clean verify

  install:
    docker:
      -image: circleci/openjdk:11

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Maven install
          command: mvn install

workflows:
  version: 2
  ci-cd-workflow:
    jobs:
      - verify
      - install:
          requires: verify
